### ISSUE TITLE
LAN Connection Shows Gibberish For File Names

### ISSUE THREAD

**Issue by bablank** [liuw086/SuperScreen#25] opened 2024-02-28 01:51 UTC
Used SuperScreen for the first time a short while ago using my Meta Quest 3. On my PC I have many 3D blu ray movies ripped to SBS 3D and hundreds of other SBS 3D videos saved over the years. On my PC and VR apps like SkyBox, BigScreen, and Pigasus the file names are recognizable such as AQUAMAN.theatrical_1.mp4. Using SuperScreen the file names appear as long strings of unintelligible letters and numbers so that I can't tell which file is which. Unless fixed SuperScreen is effectively useless to me. Hopefully you can resolve in a new update. Thanks!

**Comment by liuw086** [comment] 2024-02-28 11:58
Hello, thank you for your feedback. Can you provide some cases with specific file names? It would be better if you can have pictures or screenshots. It may be caused by the lack of corresponding fonts or character sets. I need your help to provide more information.

**Comment by bablank** [comment] 2024-02-28 22:24
![SkyBox Folders](https://github.com/liuw086/SuperScreen/assets/161541237/755a5959-9cb3-4f42-be4e-132d1d446d75)
![SuperScreen Screenshot 1](https://github.com/liuw086/SuperScreen/assets/161541237/93c28f6f-3c96-4531-ba44-8cc433b94cdc)
![SuperScreen Screenshot 2](https://github.com/liuw086/SuperScreen/assets/161541237/b0eded0b-e737-464f-be75-2149d6aafdd1)

I've attached three screenshots. Two are from the SuperScreen app and one shows my PC DNLA folders that I'm trying to access via SuperScreen. I've discovered a new and just as serious problem. I have three folders on my PC with the same name "Blu-ray 3D Movies Converted To MP4" that represent different files from three different hard drives attached to my PC. SuperScreen shows the exact same list of garbled name files no matter which folder I choose. The  first video next to the 3D Aquarium subfolder plays the file "3D SAFARI AFRICA.Title0.Bluray3DRip" which maps to a hard drive file name "3D Safari Africa.mp4" which has the former name listed in its properties detail tab. Apparently SuperScreen picks the last folder with the same name to access files from. I have other unique named folders with 3D videos that all have the garbled name issue, so I don't think the two problems are related. Hope you're able to resolve this. I like having multiple ways to play my 3D content in VR. Thanks!

**Comment by liuw086** [comment] 2024-02-29 03:14
Which DNLA server are you using? I want to deploy a similar environment for on-site restoration?

**Comment by liuw086** [comment] 2024-02-29 06:53
![image](https://github.com/liuw086/SuperScreen/assets/9710022/7364d400-b29c-499e-8844-c7ee8ed64c11)

Please help check whether there is Prettify filenames (does not rename the actual files) in your DNLA server settings. If it is turned on, it will change the file names according to its own rules. Please close it. If it is not found in your dlna service, it may be set by default and does not provide an option to close it. It’s better to change to a dlna application like 'Universal Media Server'

**Comment by liuw086** [comment] 2024-02-29 07:37
BTW, a bug was also discovered when SuperScreen displays names, because dlna media has its own path file name policy, and now I will indeed use the name it provides. I will try to release version 0.4.4 tomorrow to fix this problem. Thanks again for the clues. You can try again after upgrading this week. I'm looking forward to your feedback.

**Comment by bablank** [comment] 2024-02-29 21:24
![DNLA Video Folders Settings](https://github.com/liuw086/SuperScreen/assets/161541237/ebb242e1-182c-456f-92ad-2ea9ebfdb0f5)
![PC DNLA Server](https://github.com/liuw086/SuperScreen/assets/161541237/da379c70-68b2-4afa-aa74-368feb87f6b4)
I use my PC's built in DNLA capabilities. I set it up using Media Streaming Option in Control Panel and then mapping video folders in the Videos folder properties. Did same for pictures and music. No other fine tuning settings are available.

**Comment by liuw086** [comment] 2024-03-01 10:26
0.4.4 has been released. Please upgrade and check again to see if this problem still exists. We look forward to your reply.

**Comment by bablank** [comment] 2024-03-01 21:08
The garbled file name problem has been fixed. Thanks! However the second serious problem I identified earlier remains. I have three folders on my PC with the exact same name "Blu-ray 3D Movies Converted To MP4" that represent different files from three different hard drives attached to my PC. SuperScreen shows the exact same list of files no matter which of the three folders I choose. Apparently SuperScreen picks the last folder with the same name to access files from. Really can't use SuperScreen for all my video content without this being fixed. Sure, I could make the folder names different on each hard drive, but I shouldn't need to. Works fine on every other video app I own with DLNA access. Not sure if you consider this a high priority, but I'd really appreciate it if you could somehow fix it. I otherwise really like your app. Thanks!

**Comment by liuw086** [comment] 2024-03-02 00:08
Okay, no problem. I'll take a look at that one today.

**Comment by liuw086** [comment] 2024-03-02 13:33
I tried skybox. If it is the same folder of dlna, its performance is relatively random. Sometimes it is on hard disk A, and sometimes it is on hard disk B. The main reason is the path problem.
The problem has been found and the fix will take some time. I will try to fix it in next week's version.

**Comment by bablank** [comment] 2024-03-02 19:00
I must say I truly appreciate your super quick responsiveness. You clearly are passionate about making SuperScreen the best app in its category. It will be my go to app for viewing my PC videos once this last problem is fixed. Thanks!

**Comment by liuw086** [comment] 2024-03-08 10:47
0.4.5 has been released and online. This problem should have been fixed. Please try it. Thanks again for the feedback.

**Closed as completed** 2024-03-08 10:47 UTC
Labels: bug

**Comment by bablank** [comment] 2024-03-08 20:03
The problem is fixed! Thank you very much! SuperScreen will now be my go to app for watching my 3D videos, and I will highly recommend it. One other thing that would be super useful that I don't see in other apps (except Pigasus) would be the ability to view SBS image files in .jps, .mpo, and .jpg and even be able to slideshow them with a fixed SBS setting toggled on so that you don't have to set SBS for each picture. A toggle to swap left/right images would be helpful as well. Another nice feature would be the ability to set SBS as a viewing default in general as I sometimes watch a bunch of short SBS videos and have to toggle SBS for each one, These would all be nice to haves. If you do nothing else to SuperScreen going forward it's still an awesome video viewing app. Thanks again.

**Comment by liuw086** [comment] 2024-03-11 04:37
Thank you again for your feedback and suggestions. I will open a new issue to follow up and view the pictures.
https://github.com/liuw086/SuperScreen/issues/39
Currently, the default 3D opening method and quick switching between the previous and next videos have been added to the settings. This is also to prepare for the next step of supporting pictures. Your suggestions are very important to me, if you have any questions please continue to add issues. Or you can contact me in real time on facebook https://www.facebook.com/profile.php?id=1634082386

**Comment by bablank** [comment] 2024-03-11 20:40
So happy to hear you plan to add SBS picture viewing, I'll follow up with any other suggestions or feedback I think of as you continue to enhance SuperScreen. Thanks!

**Comment by liuw086** [comment] 2024-03-15 12:19
0.4.6
Experimental support for image formats: now supports jpg, jps, png and other 2D/3D image formats (Already supports dlna/PC client/U disk)
images to smb next week.
One week is too short, and it may not be stable yet, and there is no sufficient testing and verification. If you find any problems, please contact me and I will fix them as soon as possible. Thanks for the feedback

**Comment by bablank** [comment] 2024-03-15 23:59
Just tested the latest updates for SBS 3D image viewing. Some issues:

1. Only .jpg pics were accessible. Folders with .jps extensions showed as empty. Fortunately I always save a .jpg copy of each .jps pic in separate folders, so I was able to test the 3D.
2. All my SBS images showed in 3D but the left and right images were swapped such that what should be pop out showed as depth and vice versa. Not proper 3D in this case. My PC 3D viewing software always shows then correctly, so not sure why they appear swapped in your app. It would be awesome if you could fix this but also make perhaps the Y or X button swap left / right images so that any image that doesn't display properly can be fixed with the press of a button. This would be useful for 3D SBS videos as well as some of mine that I saved from the internet over the years are swapped. My PC viewing app enables me to swap sides with a keystroke. FYI, I'm able to see 3D SBS videos and pictures on my PC because I have Nvidia's 3D Vision goggles and software and a 3D emitter built into my monitor. I've resisted updating my video driver as Nvidia no longer supports 3D Vision. I would prefer to be able to do all my 3D viewing in VR. Your app would be the only one to properly support 3D SBS image files if you're able to implement this capability.
3. Viewed a bunch of 2D .jpg pics. For some strange reason some appear tipped to the left so they appear sideways even though they're actually in portrait mode. Hopefully you can fix this. Regardless, it would be great to have perhaps the X or Y button rotate an image to the right. 
4. Meant to tell you this sooner but forgot. The Now Playing line at the top of the SuperScreen display shows the garbled file name per my initial issue in this thread. Seems you would simply switch to using the proper name as now displayed in the folder list to fix this.

Another nice to have would to be able to toggle between pictures or videos by tapping the left joystick right for the next picture or video and tapping left to go in reverse. That would avoid the tedium of having to always click on the next icon using a pointer technique. Would then be very relaxing to toggle through a bunch of files.

That's all for now, Keep up the great work. SuperScreen is awesome.

**Comment by liuw086** [comment] 2024-03-16 08:17
Thank you for your detailed feedback

1 I checked the first problem. This should be a bug of dlna. When I use UMS to view it, it will filter out files with jps suffix. This problem is theoretically the same as other players cannot read jps through upnp. Files can be viewed using the PC client I developed myself or by copying the jps files to Quest. Unfortunately, I have researched the dlna settings of UMS and cannot find a place where I can configure the filter file suffix.

2 For your convenience, please provide some screenshots or your SBS picture materials. I will take a look at how to solve the problem.

3 and 4 would be best if you could also provide a screenshot, including how the garbled characters are correctly displayed on your computer.

I was a little hesitant when switching the joystick left and right. After all, the video corresponds to fast forward and rewind, and the picture corresponds to the previous and next, so the behavior is a bit different. But after trying it out, it felt more comfortable to use when there were more pictures, so I kept it. I’ll figure out how to optimize it later.

Thanks again for your advice！

**Comment by bablank** [comment] 2024-03-16 18:41
Here's a few SBS pics from my  PC:

![3D Camera](https://github.com/liuw086/SuperScreen/assets/161541237/eb750f0c-b2e1-4b2b-acf6-cc7c5262ce4c)
![3d cross eye image in paint 2](https://github.com/liuw086/SuperScreen/assets/161541237/eda018fe-f7bb-4f02-871b-1496e1d2b8cf)
![3d cross eye image in paint](https://github.com/liuw086/SuperScreen/assets/161541237/4040231f-76e6-4183-95c5-0cc0372b24e2)
![3D_stereoscopic_tesseract](https://github.com/liuw086/SuperScreen/assets/161541237/11c1c23a-44d7-44ec-83f8-510069c39a9e)

Here's the same images as displayed in SuperScreen but left right images appear to be swapped such that popout is depth and vice versa so that they look screwed up.:

![3D Pic 1](https://github.com/liuw086/SuperScreen/assets/161541237/414c4ca0-7bc7-4b2c-b9fa-6cdea854b7b4)
![3D Pic 2](https://github.com/liuw086/SuperScreen/assets/161541237/dbad6fc4-aad1-4a38-b5da-9f116bf04310)
![3D Pic 3](https://github.com/liuw086/SuperScreen/assets/161541237/c0c991e1-e16e-4bc8-b395-2ffb549d61e7)
![3D Pic 4](https://github.com/liuw086/SuperScreen/assets/161541237/e60dba51-e4fc-4548-9c99-b9f002e0c6ff)

Note the Now Playing gibberish name vs the files names displayed in the file selection screen.

Here's a 2D pic from my PC that is in portrait mode:

![Brennan   Gareth 03-05-2024](https://github.com/liuw086/SuperScreen/assets/161541237/5856937c-17d2-4754-b05a-6c62cfdc37be)

And here's how it looks in SuperScreen:

![2D Portrait Pic Tilted Left](https://github.com/liuw086/SuperScreen/assets/161541237/e021e421-a226-4d59-8f8a-e1bf3140e592)

Note that the file name is the first one on the file list "Brennan & Gareth 03-05-2024" but Now Playing shows a gibberish name.

Hope this helps. Another idea occurred to me. I typically like to view personal photos in descending order by date. Would be nice to be able to apply different sort orders such as  ascending/ descending by name or date modified. Thanks for your quick responses to my feedback. Happy to help in any way I can to improve SuperScreen.

**Comment by liuw086** [comment] 2024-03-17 05:35
Thank you so much, the information provided is very helpful to me, I will deal with it as soon as possible

**Comment by liuw086** [comment] 2024-03-22 09:18
bablank
0.4.8 was just updated today, adding video/photo rotation; SBS left and right perspective swap; the garbled code being played at the top of the screen should also be fixed. I still need more time to sort the files and will add it as soon as next week. At the same time, an option for automatic 3D recognition has been added in the settings, welcome to try it out
Thanks again for the pictures and screenshots. If you find any questions or suggestions, please continue to send them to me.
By the way, the kid in the photo is so cute, ❤️

**Comment by liuw086** [comment] 2024-03-22 09:19
have a nice weekend！

**Comment by bablank** [comment] 2024-03-23 17:22
Just checked out your updates. What an incredible enhancement! I can now see my SBS 3D pictures properly by being able to swap left/right views. So happy about that. They look awesome. Names are also displaying properly in the Now Playing line. I see you added the ability to rotate images which is great. However, I would recommend having it rotate to the right instead of to the left or add rotate icons for left and right. The reason is that I have to rotate my 2D pictures that are tilted left three times for them to appear correctly whereas I would have only needed to rotate them once if it were to the right. Thanks again for making these wonderful enhancements.

**Comment by liuw086** [comment] 2024-03-24 03:39
Improvement suggestions have been received. 
I will add optimization of this rotation operation in next week's version. 
Thank you again.
